name: CI

on: [push]

jobs:

  macOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test

  iOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          set -o pipefail
          xcodebuild test \
            -scheme SwiftCF \
            -destination "platform=iOS Simulator,name=iPhone 12" | xcpretty

  Linux:
    strategy:
      matrix:
        swift_version: ['5.1', '5.2', '5.3']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.swift_version }}
    steps:
      - uses: actions/checkout@v1
      - run: swift build
